#        _          _ ______ _____ _____
#       (_)        | |  ____|  __ \_   _|
#  _ __  ___  _____| | |__  | |  | || |
# | '_ \| \ \/ / _ \ |  __| | |  | || |
# | |_) | |>  <  __/ | |____| |__| || |_
# | .__/|_/_/\_\___|_|______|_____/_____|
# | |
# |_|
# https://links.pixeledi.eu
# ESPHome Kurs | 09.2024
#

substitutions:
 device_name: office
 device_board: seeed_xiao_esp32c3
 device_type: arduino

packages:
  base: !include ../00_common/main.yaml

switch:
  - platform: gpio
    pin: GPIO9
    id: myled
    on_turn_on:
      - mqtt.publish:
          topic: "office/myled"
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: "office/myled"
          payload: "OFF"    

interval:
  - interval: 1s
    then:
      - switch.toggle: myled