#        _          _ ______ _____ _____
#       (_)        | |  ____|  __ \_   _|
#  _ __  ___  _____| | |__  | |  | || |
# | '_ \| \ \/ / _ \ |  __| | |  | || |
# | |_) | |>  <  __/ | |____| |__| || |_
# | .__/|_/_/\_\___|_|______|_____/_____|
# | |
# |_|
# https://links.pixeledi.eu
# ESPHome Kurs | 09.2024
#
#
#                        ESP32 XIAO
#                        +---------+
#                    D0  2        5V 
#                    D1  3       GND 
#                    D2  4       3V3 
#                    D3  5        10 D10    
#                    D4  6         9 D9     
#                    D5  7         8 D8
#                    D6  21       20 D7
#                        +---------+

substitutions:
  device_name: office
  device_board: seeed_xiao_esp32c3
  device_type: arduino
  max_val: "30"

packages:
  base: !include ../00_common/main.yaml

sensor:
  - platform: rotary_encoder
    id: rotary1
    name: "Rotary Encoder"
    restore_mode: ALWAYS_ZERO
    pin_a: GPIO20 #clk
    pin_b: GPIO8 #dt
    min_value: 0
    max_value: $max_val
    on_value:
      - lambda: |-
          id(led).set_level(x/$max_val);

output:
  - platform: ledc
    id: led
    pin: GPIO10

light:
  - platform: monochromatic
    name: "Dimmbare LED"
    output: led